/*
    ChibiOS - Copyright (C) 2006..2016 Giovanni Di Sirio
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/*
    Generated by gen-board.h.py based on /Users/ben/code/gameoflife/firmware/board.yaml
*/

#ifndef _BOARD_H_
#define _BOARD_H_


/*
    Setup for Game of Life v1.0
*/

/*
    Board identifier
*/
#define BOARD_
#define BOARD_NAME                     "Game of Life v1.0"

/*
    Board oscillators-related settings.
*/
#if !defined(STM32_LSECLK)
#define STM32_LSECLK                   0U
#endif

#if !defined(STM32_HSECLK)
#define STM32_HSECLK                   0U
#endif

/*
    Board voltages
    Required for performance limits calculation.
*/
#define STM32_VDD                      330U

/*
    MCU type as defined in the ST header.
*/
#define STM32F030xx

/*
    IO pins assignments.
*/

#define GPIOA_COL_FET_1                0U
#define GPIOA_COL_FET_2                1U
#define GPIOA_COL_FET_3                2U
#define GPIOA_COL_FET_4                3U
#define GPIOA_COL_FET_5                4U
#define GPIOA_COL_FET_6                5U
#define GPIOA_COL_FET_7                6U
#define GPIOA_COL_FET_8                7U
#define GPIOA_ROW_FET_5                8U
#define GPIOA_ROW_FET_6                9U
#define GPIOA_G_UART                   10U
#define GPIOA_ROW_FET_8                11U
#define GPIOA_ROW_FET_1                12U
#define GPIOA_ROW_FET_2                13U
#define GPIOA_ROW_FET_3                14U
#define GPIOA_ROW_FET_4                15U

#define GPIOB_COMMS_UP                 0U
#define GPIOB_COMMS_DOWN               1U
#define GPIOB_ROW3                     2U
#define GPIOB_ROW4                     3U
#define GPIOB_ROW5                     4U
#define GPIOB_ROW6                     5U
#define GPIOB_ROW7                     6U
#define GPIOB_ROW8                     7U
#define GPIOB_COL7                     8U
#define GPIOB_COL6                     9U
#define GPIOB_COL3                     10U
#define GPIOB_COL4                     11U
#define GPIOB_COL2                     12U
#define GPIOB_COL1                     13U
#define GPIOB_COL5                     14U
#define GPIOB_ROW_FET_7                15U

#define GPIOC_PIN0                     0U
#define GPIOC_PIN1                     1U
#define GPIOC_PIN2                     2U
#define GPIOC_PIN3                     3U
#define GPIOC_PIN4                     4U
#define GPIOC_PIN5                     5U
#define GPIOC_PIN6                     6U
#define GPIOC_PIN7                     7U
#define GPIOC_PIN8                     8U
#define GPIOC_PIN9                     9U
#define GPIOC_PIN10                    10U
#define GPIOC_PIN11                    11U
#define GPIOC_PIN12                    12U
#define GPIOC_COMMS_RIGHT              13U
#define GPIOC_COMMS_LEFT               14U
#define GPIOC_COL8                     15U

#define GPIOD_PIN0                     0U
#define GPIOD_PIN1                     1U
#define GPIOD_PIN2                     2U
#define GPIOD_PIN3                     3U
#define GPIOD_PIN4                     4U
#define GPIOD_PIN5                     5U
#define GPIOD_PIN6                     6U
#define GPIOD_PIN7                     7U
#define GPIOD_PIN8                     8U
#define GPIOD_PIN9                     9U
#define GPIOD_PIN10                    10U
#define GPIOD_PIN11                    11U
#define GPIOD_PIN12                    12U
#define GPIOD_PIN13                    13U
#define GPIOD_PIN14                    14U
#define GPIOD_PIN15                    15U

#define GPIOF_ROW1                     0U
#define GPIOF_ROW2                     1U
#define GPIOF_PIN2                     2U
#define GPIOF_PIN3                     3U
#define GPIOF_PIN4                     4U
#define GPIOF_PIN5                     5U
#define GPIOF_SHIFT_LEFT               6U
#define GPIOF_SHIFT_RIGHT              7U
#define GPIOF_PIN8                     8U
#define GPIOF_PIN9                     9U
#define GPIOF_PIN10                    10U
#define GPIOF_PIN11                    11U
#define GPIOF_PIN12                    12U
#define GPIOF_PIN13                    13U
#define GPIOF_PIN14                    14U
#define GPIOF_PIN15                    15U

/*
    IO lines assignments.
*/

#define LINE_COL1                      PAL_LINE(GPIOB, 13U)
#define LINE_COL2                      PAL_LINE(GPIOB, 12U)
#define LINE_COL3                      PAL_LINE(GPIOB, 10U)
#define LINE_COL4                      PAL_LINE(GPIOB, 11U)
#define LINE_COL5                      PAL_LINE(GPIOB, 14U)
#define LINE_COL6                      PAL_LINE(GPIOB, 9U)
#define LINE_COL7                      PAL_LINE(GPIOB, 8U)
#define LINE_COL8                      PAL_LINE(GPIOC, 15U)
#define LINE_COL_FET_1                 PAL_LINE(GPIOA, 0U)
#define LINE_COL_FET_2                 PAL_LINE(GPIOA, 1U)
#define LINE_COL_FET_3                 PAL_LINE(GPIOA, 2U)
#define LINE_COL_FET_4                 PAL_LINE(GPIOA, 3U)
#define LINE_COL_FET_5                 PAL_LINE(GPIOA, 4U)
#define LINE_COL_FET_6                 PAL_LINE(GPIOA, 5U)
#define LINE_COL_FET_7                 PAL_LINE(GPIOA, 6U)
#define LINE_COL_FET_8                 PAL_LINE(GPIOA, 7U)
#define LINE_COMMS_DOWN                PAL_LINE(GPIOB, 1U)
#define LINE_COMMS_LEFT                PAL_LINE(GPIOC, 14U)
#define LINE_COMMS_RIGHT               PAL_LINE(GPIOC, 13U)
#define LINE_COMMS_UP                  PAL_LINE(GPIOB, 0U)
#define LINE_G_UART                    PAL_LINE(GPIOA, 10U)
#define LINE_ROW1                      PAL_LINE(GPIOF, 0U)
#define LINE_ROW2                      PAL_LINE(GPIOF, 1U)
#define LINE_ROW3                      PAL_LINE(GPIOB, 2U)
#define LINE_ROW4                      PAL_LINE(GPIOB, 3U)
#define LINE_ROW5                      PAL_LINE(GPIOB, 4U)
#define LINE_ROW6                      PAL_LINE(GPIOB, 5U)
#define LINE_ROW7                      PAL_LINE(GPIOB, 6U)
#define LINE_ROW8                      PAL_LINE(GPIOB, 7U)
#define LINE_ROW_FET_1                 PAL_LINE(GPIOA, 12U)
#define LINE_ROW_FET_2                 PAL_LINE(GPIOA, 13U)
#define LINE_ROW_FET_3                 PAL_LINE(GPIOA, 14U)
#define LINE_ROW_FET_4                 PAL_LINE(GPIOA, 15U)
#define LINE_ROW_FET_5                 PAL_LINE(GPIOA, 8U)
#define LINE_ROW_FET_6                 PAL_LINE(GPIOA, 9U)
#define LINE_ROW_FET_7                 PAL_LINE(GPIOB, 15U)
#define LINE_ROW_FET_8                 PAL_LINE(GPIOA, 11U)
#define LINE_SHIFT_LEFT                PAL_LINE(GPIOF, 6U)
#define LINE_SHIFT_RIGHT               PAL_LINE(GPIOF, 7U)

/*
    I/O ports initial setup, this configuration is established soon after reset
    in the initialization code.
     Please refer to the STM32 Reference Manual for details.
*/
#define PIN_MODE_INPUT(n)              (0U << ((n) * 2U))
#define PIN_MODE_OUTPUT(n)             (1U << ((n) * 2U))
#define PIN_MODE_ALTERNATE(n)          (2U << ((n) * 2U))
#define PIN_MODE_ANALOG(n)             (3U << ((n) * 2U))
#define PIN_OD_LOW(n)                  (0U << (n))
#define PIN_OD_HIGH(n)                 (1U << (n))
#define PIN_OTYPE_PUSHPULL(n)          (0U << (n))
#define PIN_OTYPE_OPENDRAIN(n)         (1U << (n))
#define PIN_OSPEED_VERYLOW(n)          (0U << ((n) * 2U))
#define PIN_OSPEED_LOW(n)              (1U << ((n) * 2U))
#define PIN_OSPEED_MEDIUM(n)           (2U << ((n) * 2U))
#define PIN_OSPEED_HIGH(n)             (3U << ((n) * 2U))
#define PIN_PUPD_FLOATING(n)           (0U << ((n) * 2U))
#define PIN_PUPD_PULLUP(n)             (1U << ((n) * 2U))
#define PIN_PUPD_PULLDOWN(n)           (2U << ((n) * 2U))
#define PIN_AFIO_AF(n, v)              ((v) << (((n) % 8U) * 4U))

/*
 *  GPIOA setup:
 *
 * PA0  - COL_FET_1                    (output, pushpull).
 * PA1  - COL_FET_2                    (output, pushpull).
 * PA2  - COL_FET_3                    (output, pushpull).
 * PA3  - COL_FET_4                    (output, pushpull).
 * PA4  - COL_FET_5                    (output, pushpull).
 * PA5  - COL_FET_6                    (output, pushpull).
 * PA6  - COL_FET_7                    (output, pushpull).
 * PA7  - COL_FET_8                    (output, pushpull).
 * PA8  - ROW_FET_5                    (output, pushpull).
 * PA9  - ROW_FET_6                    (output, pushpull).
 * PA10 - G_UART                       (input, floating).
 * PA11 - ROW_FET_8                    (output, pushpull).
 * PA12 - ROW_FET_1                    (output, pushpull).
 * PA13 - ROW_FET_2                    (output, pushpull).
 * PA14 - ROW_FET_3                    (output, pushpull).
 * PA15 - ROW_FET_4                    (output, pushpull).
*/
#define VAL_GPIOA_MODER                (PIN_MODE_OUTPUT(GPIOA_COL_FET_1) | \
                                        PIN_MODE_OUTPUT(GPIOA_COL_FET_2) | \
                                        PIN_MODE_OUTPUT(GPIOA_COL_FET_3) | \
                                        PIN_MODE_OUTPUT(GPIOA_COL_FET_4) | \
                                        PIN_MODE_OUTPUT(GPIOA_COL_FET_5) | \
                                        PIN_MODE_OUTPUT(GPIOA_COL_FET_6) | \
                                        PIN_MODE_OUTPUT(GPIOA_COL_FET_7) | \
                                        PIN_MODE_OUTPUT(GPIOA_COL_FET_8) | \
                                        PIN_MODE_OUTPUT(GPIOA_ROW_FET_5) | \
                                        PIN_MODE_OUTPUT(GPIOA_ROW_FET_6) | \
                                        PIN_MODE_INPUT(GPIOA_G_UART) | \
                                        PIN_MODE_OUTPUT(GPIOA_ROW_FET_8) | \
                                        PIN_MODE_OUTPUT(GPIOA_ROW_FET_1) | \
                                        PIN_MODE_OUTPUT(GPIOA_ROW_FET_2) | \
                                        PIN_MODE_OUTPUT(GPIOA_ROW_FET_3) | \
                                        PIN_MODE_OUTPUT(GPIOA_ROW_FET_4))
#define VAL_GPIOA_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOA_COL_FET_1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_COL_FET_2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_COL_FET_3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_COL_FET_4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_COL_FET_5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_COL_FET_6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_COL_FET_7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_COL_FET_8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_ROW_FET_5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_ROW_FET_6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_G_UART) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_ROW_FET_8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_ROW_FET_1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_ROW_FET_2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_ROW_FET_3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_ROW_FET_4))
#define VAL_GPIOA_OSPEEDR              (PIN_OSPEED_HIGH(GPIOA_COL_FET_1) | \
                                        PIN_OSPEED_HIGH(GPIOA_COL_FET_2) | \
                                        PIN_OSPEED_HIGH(GPIOA_COL_FET_3) | \
                                        PIN_OSPEED_HIGH(GPIOA_COL_FET_4) | \
                                        PIN_OSPEED_HIGH(GPIOA_COL_FET_5) | \
                                        PIN_OSPEED_HIGH(GPIOA_COL_FET_6) | \
                                        PIN_OSPEED_HIGH(GPIOA_COL_FET_7) | \
                                        PIN_OSPEED_HIGH(GPIOA_COL_FET_8) | \
                                        PIN_OSPEED_HIGH(GPIOA_ROW_FET_5) | \
                                        PIN_OSPEED_HIGH(GPIOA_ROW_FET_6) | \
                                        PIN_OSPEED_HIGH(GPIOA_G_UART) | \
                                        PIN_OSPEED_HIGH(GPIOA_ROW_FET_8) | \
                                        PIN_OSPEED_HIGH(GPIOA_ROW_FET_1) | \
                                        PIN_OSPEED_HIGH(GPIOA_ROW_FET_2) | \
                                        PIN_OSPEED_HIGH(GPIOA_ROW_FET_3) | \
                                        PIN_OSPEED_HIGH(GPIOA_ROW_FET_4))
#define VAL_GPIOA_PUPDR                (PIN_PUPD_PULLUP(GPIOA_COL_FET_1) | \
                                        PIN_PUPD_PULLUP(GPIOA_COL_FET_2) | \
                                        PIN_PUPD_PULLUP(GPIOA_COL_FET_3) | \
                                        PIN_PUPD_PULLUP(GPIOA_COL_FET_4) | \
                                        PIN_PUPD_PULLUP(GPIOA_COL_FET_5) | \
                                        PIN_PUPD_PULLUP(GPIOA_COL_FET_6) | \
                                        PIN_PUPD_PULLUP(GPIOA_COL_FET_7) | \
                                        PIN_PUPD_PULLUP(GPIOA_COL_FET_8) | \
                                        PIN_PUPD_PULLUP(GPIOA_ROW_FET_5) | \
                                        PIN_PUPD_PULLUP(GPIOA_ROW_FET_6) | \
                                        PIN_PUPD_FLOATING(GPIOA_G_UART) | \
                                        PIN_PUPD_PULLUP(GPIOA_ROW_FET_8) | \
                                        PIN_PUPD_PULLUP(GPIOA_ROW_FET_1) | \
                                        PIN_PUPD_PULLUP(GPIOA_ROW_FET_2) | \
                                        PIN_PUPD_PULLUP(GPIOA_ROW_FET_3) | \
                                        PIN_PUPD_PULLUP(GPIOA_ROW_FET_4))
#define VAL_GPIOA_ODR                  (PIN_OD_HIGH(GPIOA_COL_FET_1) | \
                                        PIN_OD_HIGH(GPIOA_COL_FET_2) | \
                                        PIN_OD_HIGH(GPIOA_COL_FET_3) | \
                                        PIN_OD_HIGH(GPIOA_COL_FET_4) | \
                                        PIN_OD_HIGH(GPIOA_COL_FET_5) | \
                                        PIN_OD_HIGH(GPIOA_COL_FET_6) | \
                                        PIN_OD_HIGH(GPIOA_COL_FET_7) | \
                                        PIN_OD_HIGH(GPIOA_COL_FET_8) | \
                                        PIN_OD_HIGH(GPIOA_ROW_FET_5) | \
                                        PIN_OD_HIGH(GPIOA_ROW_FET_6) | \
                                        PIN_OD_HIGH(GPIOA_G_UART) | \
                                        PIN_OD_HIGH(GPIOA_ROW_FET_8) | \
                                        PIN_OD_HIGH(GPIOA_ROW_FET_1) | \
                                        PIN_OD_HIGH(GPIOA_ROW_FET_2) | \
                                        PIN_OD_HIGH(GPIOA_ROW_FET_3) | \
                                        PIN_OD_HIGH(GPIOA_ROW_FET_4))
#define VAL_GPIOA_AFRL                 (PIN_AFIO_AF(GPIOA_COL_FET_1, 0U) | \
                                        PIN_AFIO_AF(GPIOA_COL_FET_2, 0U) | \
                                        PIN_AFIO_AF(GPIOA_COL_FET_3, 0U) | \
                                        PIN_AFIO_AF(GPIOA_COL_FET_4, 0U) | \
                                        PIN_AFIO_AF(GPIOA_COL_FET_5, 0U) | \
                                        PIN_AFIO_AF(GPIOA_COL_FET_6, 0U) | \
                                        PIN_AFIO_AF(GPIOA_COL_FET_7, 0U) | \
                                        PIN_AFIO_AF(GPIOA_COL_FET_8, 0U))
#define VAL_GPIOA_AFRH                 (PIN_AFIO_AF(GPIOA_ROW_FET_5, 0U) | \
                                        PIN_AFIO_AF(GPIOA_ROW_FET_6, 0U) | \
                                        PIN_AFIO_AF(GPIOA_G_UART, 0U) | \
                                        PIN_AFIO_AF(GPIOA_ROW_FET_8, 0U) | \
                                        PIN_AFIO_AF(GPIOA_ROW_FET_1, 0U) | \
                                        PIN_AFIO_AF(GPIOA_ROW_FET_2, 0U) | \
                                        PIN_AFIO_AF(GPIOA_ROW_FET_3, 0U) | \
                                        PIN_AFIO_AF(GPIOA_ROW_FET_4, 0U))

/*
 *  GPIOB setup:
 *
 * PB0  - COMMS_UP                     (input, floating).
 * PB1  - COMMS_DOWN                   (input, floating).
 * PB2  - ROW3                         (analog, floating).
 * PB3  - ROW4                         (analog, floating).
 * PB4  - ROW5                         (analog, floating).
 * PB5  - ROW6                         (analog, floating).
 * PB6  - ROW7                         (analog, floating).
 * PB7  - ROW8                         (analog, floating).
 * PB8  - COL7                         (analog, floating).
 * PB9  - COL6                         (analog, floating).
 * PB10 - COL3                         (analog, floating).
 * PB11 - COL4                         (analog, floating).
 * PB12 - COL2                         (analog, floating).
 * PB13 - COL1                         (analog, floating).
 * PB14 - COL5                         (analog, floating).
 * PB15 - ROW_FET_7                    (output, pushpull).
*/
#define VAL_GPIOB_MODER                (PIN_MODE_INPUT(GPIOB_COMMS_UP) | \
                                        PIN_MODE_INPUT(GPIOB_COMMS_DOWN) | \
                                        PIN_MODE_ANALOG(GPIOB_ROW3) | \
                                        PIN_MODE_ANALOG(GPIOB_ROW4) | \
                                        PIN_MODE_ANALOG(GPIOB_ROW5) | \
                                        PIN_MODE_ANALOG(GPIOB_ROW6) | \
                                        PIN_MODE_ANALOG(GPIOB_ROW7) | \
                                        PIN_MODE_ANALOG(GPIOB_ROW8) | \
                                        PIN_MODE_ANALOG(GPIOB_COL7) | \
                                        PIN_MODE_ANALOG(GPIOB_COL6) | \
                                        PIN_MODE_ANALOG(GPIOB_COL3) | \
                                        PIN_MODE_ANALOG(GPIOB_COL4) | \
                                        PIN_MODE_ANALOG(GPIOB_COL2) | \
                                        PIN_MODE_ANALOG(GPIOB_COL1) | \
                                        PIN_MODE_ANALOG(GPIOB_COL5) | \
                                        PIN_MODE_OUTPUT(GPIOB_ROW_FET_7))
#define VAL_GPIOB_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOB_COMMS_UP) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_COMMS_DOWN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_ROW3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_ROW4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_ROW5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_ROW6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_ROW7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_ROW8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_COL7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_COL6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_COL3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_COL4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_COL2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_COL1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_COL5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_ROW_FET_7))
#define VAL_GPIOB_OSPEEDR              (PIN_OSPEED_HIGH(GPIOB_COMMS_UP) | \
                                        PIN_OSPEED_HIGH(GPIOB_COMMS_DOWN) | \
                                        PIN_OSPEED_HIGH(GPIOB_ROW3) | \
                                        PIN_OSPEED_HIGH(GPIOB_ROW4) | \
                                        PIN_OSPEED_HIGH(GPIOB_ROW5) | \
                                        PIN_OSPEED_HIGH(GPIOB_ROW6) | \
                                        PIN_OSPEED_HIGH(GPIOB_ROW7) | \
                                        PIN_OSPEED_HIGH(GPIOB_ROW8) | \
                                        PIN_OSPEED_HIGH(GPIOB_COL7) | \
                                        PIN_OSPEED_HIGH(GPIOB_COL6) | \
                                        PIN_OSPEED_HIGH(GPIOB_COL3) | \
                                        PIN_OSPEED_HIGH(GPIOB_COL4) | \
                                        PIN_OSPEED_HIGH(GPIOB_COL2) | \
                                        PIN_OSPEED_HIGH(GPIOB_COL1) | \
                                        PIN_OSPEED_HIGH(GPIOB_COL5) | \
                                        PIN_OSPEED_HIGH(GPIOB_ROW_FET_7))
#define VAL_GPIOB_PUPDR                (PIN_PUPD_FLOATING(GPIOB_COMMS_UP) | \
                                        PIN_PUPD_FLOATING(GPIOB_COMMS_DOWN) | \
                                        PIN_PUPD_FLOATING(GPIOB_ROW3) | \
                                        PIN_PUPD_FLOATING(GPIOB_ROW4) | \
                                        PIN_PUPD_FLOATING(GPIOB_ROW5) | \
                                        PIN_PUPD_FLOATING(GPIOB_ROW6) | \
                                        PIN_PUPD_FLOATING(GPIOB_ROW7) | \
                                        PIN_PUPD_FLOATING(GPIOB_ROW8) | \
                                        PIN_PUPD_FLOATING(GPIOB_COL7) | \
                                        PIN_PUPD_FLOATING(GPIOB_COL6) | \
                                        PIN_PUPD_FLOATING(GPIOB_COL3) | \
                                        PIN_PUPD_FLOATING(GPIOB_COL4) | \
                                        PIN_PUPD_FLOATING(GPIOB_COL2) | \
                                        PIN_PUPD_FLOATING(GPIOB_COL1) | \
                                        PIN_PUPD_FLOATING(GPIOB_COL5) | \
                                        PIN_PUPD_PULLUP(GPIOB_ROW_FET_7))
#define VAL_GPIOB_ODR                  (PIN_OD_HIGH(GPIOB_COMMS_UP) | \
                                        PIN_OD_HIGH(GPIOB_COMMS_DOWN) | \
                                        PIN_OD_HIGH(GPIOB_ROW3) | \
                                        PIN_OD_HIGH(GPIOB_ROW4) | \
                                        PIN_OD_HIGH(GPIOB_ROW5) | \
                                        PIN_OD_HIGH(GPIOB_ROW6) | \
                                        PIN_OD_HIGH(GPIOB_ROW7) | \
                                        PIN_OD_HIGH(GPIOB_ROW8) | \
                                        PIN_OD_HIGH(GPIOB_COL7) | \
                                        PIN_OD_HIGH(GPIOB_COL6) | \
                                        PIN_OD_HIGH(GPIOB_COL3) | \
                                        PIN_OD_HIGH(GPIOB_COL4) | \
                                        PIN_OD_HIGH(GPIOB_COL2) | \
                                        PIN_OD_HIGH(GPIOB_COL1) | \
                                        PIN_OD_HIGH(GPIOB_COL5) | \
                                        PIN_OD_HIGH(GPIOB_ROW_FET_7))
#define VAL_GPIOB_AFRL                 (PIN_AFIO_AF(GPIOB_COMMS_UP, 0U) | \
                                        PIN_AFIO_AF(GPIOB_COMMS_DOWN, 0U) | \
                                        PIN_AFIO_AF(GPIOB_ROW3, 0U) | \
                                        PIN_AFIO_AF(GPIOB_ROW4, 0U) | \
                                        PIN_AFIO_AF(GPIOB_ROW5, 0U) | \
                                        PIN_AFIO_AF(GPIOB_ROW6, 0U) | \
                                        PIN_AFIO_AF(GPIOB_ROW7, 0U) | \
                                        PIN_AFIO_AF(GPIOB_ROW8, 0U))
#define VAL_GPIOB_AFRH                 (PIN_AFIO_AF(GPIOB_COL7, 0U) | \
                                        PIN_AFIO_AF(GPIOB_COL6, 0U) | \
                                        PIN_AFIO_AF(GPIOB_COL3, 0U) | \
                                        PIN_AFIO_AF(GPIOB_COL4, 0U) | \
                                        PIN_AFIO_AF(GPIOB_COL2, 0U) | \
                                        PIN_AFIO_AF(GPIOB_COL1, 0U) | \
                                        PIN_AFIO_AF(GPIOB_COL5, 0U) | \
                                        PIN_AFIO_AF(GPIOB_ROW_FET_7, 0U))

/*
 *  GPIOC setup:
 *
 * PC0  - PIN0                         (unused).
 * PC1  - PIN1                         (unused).
 * PC2  - PIN2                         (unused).
 * PC3  - PIN3                         (unused).
 * PC4  - PIN4                         (unused).
 * PC5  - PIN5                         (unused).
 * PC6  - PIN6                         (unused).
 * PC7  - PIN7                         (unused).
 * PC8  - PIN8                         (unused).
 * PC9  - PIN9                         (unused).
 * PC10 - PIN10                        (unused).
 * PC11 - PIN11                        (unused).
 * PC12 - PIN12                        (unused).
 * PC13 - COMMS_RIGHT                  (input, floating).
 * PC14 - COMMS_LEFT                   (input, floating).
 * PC15 - COL8                         (analog, floating).
*/
#define VAL_GPIOC_MODER                (PIN_MODE_INPUT(GPIOC_PIN0) | \
                                        PIN_MODE_INPUT(GPIOC_PIN1) | \
                                        PIN_MODE_INPUT(GPIOC_PIN2) | \
                                        PIN_MODE_INPUT(GPIOC_PIN3) | \
                                        PIN_MODE_INPUT(GPIOC_PIN4) | \
                                        PIN_MODE_INPUT(GPIOC_PIN5) | \
                                        PIN_MODE_INPUT(GPIOC_PIN6) | \
                                        PIN_MODE_INPUT(GPIOC_PIN7) | \
                                        PIN_MODE_INPUT(GPIOC_PIN8) | \
                                        PIN_MODE_INPUT(GPIOC_PIN9) | \
                                        PIN_MODE_INPUT(GPIOC_PIN10) | \
                                        PIN_MODE_INPUT(GPIOC_PIN11) | \
                                        PIN_MODE_INPUT(GPIOC_PIN12) | \
                                        PIN_MODE_INPUT(GPIOC_COMMS_RIGHT) | \
                                        PIN_MODE_INPUT(GPIOC_COMMS_LEFT) | \
                                        PIN_MODE_ANALOG(GPIOC_COL8))
#define VAL_GPIOC_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOC_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_COMMS_RIGHT) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_COMMS_LEFT) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_COL8))
#define VAL_GPIOC_OSPEEDR              (PIN_OSPEED_HIGH(GPIOC_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOC_COMMS_RIGHT) | \
                                        PIN_OSPEED_HIGH(GPIOC_COMMS_LEFT) | \
                                        PIN_OSPEED_HIGH(GPIOC_COL8))
#define VAL_GPIOC_PUPDR                (PIN_PUPD_PULLUP(GPIOC_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN12) | \
                                        PIN_PUPD_FLOATING(GPIOC_COMMS_RIGHT) | \
                                        PIN_PUPD_FLOATING(GPIOC_COMMS_LEFT) | \
                                        PIN_PUPD_FLOATING(GPIOC_COL8))
#define VAL_GPIOC_ODR                  (PIN_OD_HIGH(GPIOC_PIN0) | \
                                        PIN_OD_HIGH(GPIOC_PIN1) | \
                                        PIN_OD_HIGH(GPIOC_PIN2) | \
                                        PIN_OD_HIGH(GPIOC_PIN3) | \
                                        PIN_OD_HIGH(GPIOC_PIN4) | \
                                        PIN_OD_HIGH(GPIOC_PIN5) | \
                                        PIN_OD_HIGH(GPIOC_PIN6) | \
                                        PIN_OD_HIGH(GPIOC_PIN7) | \
                                        PIN_OD_HIGH(GPIOC_PIN8) | \
                                        PIN_OD_HIGH(GPIOC_PIN9) | \
                                        PIN_OD_HIGH(GPIOC_PIN10) | \
                                        PIN_OD_HIGH(GPIOC_PIN11) | \
                                        PIN_OD_HIGH(GPIOC_PIN12) | \
                                        PIN_OD_HIGH(GPIOC_COMMS_RIGHT) | \
                                        PIN_OD_HIGH(GPIOC_COMMS_LEFT) | \
                                        PIN_OD_HIGH(GPIOC_COL8))
#define VAL_GPIOC_AFRL                 (PIN_AFIO_AF(GPIOC_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN7, 0U))
#define VAL_GPIOC_AFRH                 (PIN_AFIO_AF(GPIOC_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOC_COMMS_RIGHT, 0U) | \
                                        PIN_AFIO_AF(GPIOC_COMMS_LEFT, 0U) | \
                                        PIN_AFIO_AF(GPIOC_COL8, 0U))

/*
 *  GPIOD setup:
 *
 * PD0  - PIN0                         (unused).
 * PD1  - PIN1                         (unused).
 * PD2  - PIN2                         (unused).
 * PD3  - PIN3                         (unused).
 * PD4  - PIN4                         (unused).
 * PD5  - PIN5                         (unused).
 * PD6  - PIN6                         (unused).
 * PD7  - PIN7                         (unused).
 * PD8  - PIN8                         (unused).
 * PD9  - PIN9                         (unused).
 * PD10 - PIN10                        (unused).
 * PD11 - PIN11                        (unused).
 * PD12 - PIN12                        (unused).
 * PD13 - PIN13                        (unused).
 * PD14 - PIN14                        (unused).
 * PD15 - PIN15                        (unused).
*/
#define VAL_GPIOD_MODER                (PIN_MODE_INPUT(GPIOD_PIN0) | \
                                        PIN_MODE_INPUT(GPIOD_PIN1) | \
                                        PIN_MODE_INPUT(GPIOD_PIN2) | \
                                        PIN_MODE_INPUT(GPIOD_PIN3) | \
                                        PIN_MODE_INPUT(GPIOD_PIN4) | \
                                        PIN_MODE_INPUT(GPIOD_PIN5) | \
                                        PIN_MODE_INPUT(GPIOD_PIN6) | \
                                        PIN_MODE_INPUT(GPIOD_PIN7) | \
                                        PIN_MODE_INPUT(GPIOD_PIN8) | \
                                        PIN_MODE_INPUT(GPIOD_PIN9) | \
                                        PIN_MODE_INPUT(GPIOD_PIN10) | \
                                        PIN_MODE_INPUT(GPIOD_PIN11) | \
                                        PIN_MODE_INPUT(GPIOD_PIN12) | \
                                        PIN_MODE_INPUT(GPIOD_PIN13) | \
                                        PIN_MODE_INPUT(GPIOD_PIN14) | \
                                        PIN_MODE_INPUT(GPIOD_PIN15))
#define VAL_GPIOD_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOD_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN15))
#define VAL_GPIOD_OSPEEDR              (PIN_OSPEED_HIGH(GPIOD_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_PUPDR                (PIN_PUPD_PULLUP(GPIOD_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN15))
#define VAL_GPIOD_ODR                  (PIN_OD_HIGH(GPIOD_PIN0) | \
                                        PIN_OD_HIGH(GPIOD_PIN1) | \
                                        PIN_OD_HIGH(GPIOD_PIN2) | \
                                        PIN_OD_HIGH(GPIOD_PIN3) | \
                                        PIN_OD_HIGH(GPIOD_PIN4) | \
                                        PIN_OD_HIGH(GPIOD_PIN5) | \
                                        PIN_OD_HIGH(GPIOD_PIN6) | \
                                        PIN_OD_HIGH(GPIOD_PIN7) | \
                                        PIN_OD_HIGH(GPIOD_PIN8) | \
                                        PIN_OD_HIGH(GPIOD_PIN9) | \
                                        PIN_OD_HIGH(GPIOD_PIN10) | \
                                        PIN_OD_HIGH(GPIOD_PIN11) | \
                                        PIN_OD_HIGH(GPIOD_PIN12) | \
                                        PIN_OD_HIGH(GPIOD_PIN13) | \
                                        PIN_OD_HIGH(GPIOD_PIN14) | \
                                        PIN_OD_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_AFRL                 (PIN_AFIO_AF(GPIOD_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN7, 0U))
#define VAL_GPIOD_AFRH                 (PIN_AFIO_AF(GPIOD_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN15, 0U))

/*
 *  GPIOF setup:
 *
 * PF0  - ROW1                         (analog, floating).
 * PF1  - ROW2                         (analog, floating).
 * PF2  - PIN2                         (unused).
 * PF3  - PIN3                         (unused).
 * PF4  - PIN4                         (unused).
 * PF5  - PIN5                         (unused).
 * PF6  - SHIFT_LEFT                   (input, floating).
 * PF7  - SHIFT_RIGHT                  (input, floating).
 * PF8  - PIN8                         (unused).
 * PF9  - PIN9                         (unused).
 * PF10 - PIN10                        (unused).
 * PF11 - PIN11                        (unused).
 * PF12 - PIN12                        (unused).
 * PF13 - PIN13                        (unused).
 * PF14 - PIN14                        (unused).
 * PF15 - PIN15                        (unused).
*/
#define VAL_GPIOF_MODER                (PIN_MODE_ANALOG(GPIOF_ROW1) | \
                                        PIN_MODE_ANALOG(GPIOF_ROW2) | \
                                        PIN_MODE_INPUT(GPIOF_PIN2) | \
                                        PIN_MODE_INPUT(GPIOF_PIN3) | \
                                        PIN_MODE_INPUT(GPIOF_PIN4) | \
                                        PIN_MODE_INPUT(GPIOF_PIN5) | \
                                        PIN_MODE_INPUT(GPIOF_SHIFT_LEFT) | \
                                        PIN_MODE_INPUT(GPIOF_SHIFT_RIGHT) | \
                                        PIN_MODE_INPUT(GPIOF_PIN8) | \
                                        PIN_MODE_INPUT(GPIOF_PIN9) | \
                                        PIN_MODE_INPUT(GPIOF_PIN10) | \
                                        PIN_MODE_INPUT(GPIOF_PIN11) | \
                                        PIN_MODE_INPUT(GPIOF_PIN12) | \
                                        PIN_MODE_INPUT(GPIOF_PIN13) | \
                                        PIN_MODE_INPUT(GPIOF_PIN14) | \
                                        PIN_MODE_INPUT(GPIOF_PIN15))
#define VAL_GPIOF_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOF_ROW1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_ROW2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_SHIFT_LEFT) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_SHIFT_RIGHT) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN15))
#define VAL_GPIOF_OSPEEDR              (PIN_OSPEED_HIGH(GPIOF_ROW1) | \
                                        PIN_OSPEED_HIGH(GPIOF_ROW2) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOF_SHIFT_LEFT) | \
                                        PIN_OSPEED_HIGH(GPIOF_SHIFT_RIGHT) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_PUPDR                (PIN_PUPD_FLOATING(GPIOF_ROW1) | \
                                        PIN_PUPD_FLOATING(GPIOF_ROW2) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN5) | \
                                        PIN_PUPD_FLOATING(GPIOF_SHIFT_LEFT) | \
                                        PIN_PUPD_FLOATING(GPIOF_SHIFT_RIGHT) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN15))
#define VAL_GPIOF_ODR                  (PIN_OD_HIGH(GPIOF_ROW1) | \
                                        PIN_OD_HIGH(GPIOF_ROW2) | \
                                        PIN_OD_HIGH(GPIOF_PIN2) | \
                                        PIN_OD_HIGH(GPIOF_PIN3) | \
                                        PIN_OD_HIGH(GPIOF_PIN4) | \
                                        PIN_OD_HIGH(GPIOF_PIN5) | \
                                        PIN_OD_HIGH(GPIOF_SHIFT_LEFT) | \
                                        PIN_OD_HIGH(GPIOF_SHIFT_RIGHT) | \
                                        PIN_OD_HIGH(GPIOF_PIN8) | \
                                        PIN_OD_HIGH(GPIOF_PIN9) | \
                                        PIN_OD_HIGH(GPIOF_PIN10) | \
                                        PIN_OD_HIGH(GPIOF_PIN11) | \
                                        PIN_OD_HIGH(GPIOF_PIN12) | \
                                        PIN_OD_HIGH(GPIOF_PIN13) | \
                                        PIN_OD_HIGH(GPIOF_PIN14) | \
                                        PIN_OD_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_AFRL                 (PIN_AFIO_AF(GPIOF_ROW1, 0U) | \
                                        PIN_AFIO_AF(GPIOF_ROW2, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOF_SHIFT_LEFT, 0U) | \
                                        PIN_AFIO_AF(GPIOF_SHIFT_RIGHT, 0U))
#define VAL_GPIOF_AFRH                 (PIN_AFIO_AF(GPIOF_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN15, 0U))

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */